[build]
  command = "npm run build"
  publish = "dist/tienda-tenis/browser"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions]
  included_files = ["dist/tienda-tenis/server/**/*"]

[build.environment]
  NODE_VERSION = "18.19"
